### ISSUE TITLE
Github reference 

### ISSUE THREAD

**Issue by axelfj** [cgranados16/cgranados.dev#31]
# Reference is wrong
![image](https://github.com/cgranados16/cgranados.dev/assets/26331208/93567332-ea53-466d-896b-ba14c41e0ada)

I wanted to see your code but I cannot access it because it sends me to your github profile instead of the cgranados.dev repo. So I had to look it up.

**Comment by cgranados16** [comment]
Hey @axelfj,
this has been fixed in https://github.com/cgranados16/cgranados.dev/releases/tag/0.2.0 🎉

**Comment by cgranados16** [comment]
Hey @axelfj,
this has been fixed in https://github.com/cgranados16/cgranados.dev/releases/tag/0.2.0 🎉
